#!/usr/bin/env -S uv run --locked --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""The i-have-ocd store: one project's main line and parked items on this machine.

Several sessions share a project's queue, so this helper is its only writer. Each item has an
id that is never reused (shown as P<n>); a ticket number or a title is an attribute, so two
concerns on one ticket are two items. Every change runs in one transaction that checks the
version the caller read, writes the item, its new version and a history event, and records
the request id, so a retry returns the first result instead of acting twice. An item stays
pending (open, or taken under a lease) until it is closed with a receipt; a closed item is
never reopened, and a recurrence is a new item that cites the old id.

    ocd.py park "what, why, where" --source <where seen> [--tracking <ticket>] [--needs-owner] --request-id R
    ocd.py add-source P3 --source <where> [--tracking <ticket>] --expected-version V --request-id R
    ocd.py list [--all] [--text]    pending items with counts and the store revision
    ocd.py show P3 [--text]         one item and its history
    ocd.py count                    the pending number for the reply marker; ? when the store cannot be read
    ocd.py take P3 --expected-version V --request-id R [--ttl-minutes 60]      prints the lease token
    ocd.py decide P3 --ref <owner's ruling> --expected-version V --request-id R
    ocd.py done P3 --kind ticket|pr|scheduled|resolved|transferred|recorded --ref <receipt> --expected-version V --request-id R [--token T]
    ocd.py drop P3 --decision <owner's ruling> --expected-version V --request-id R [--token T]
    ocd.py main get [--text]
    ocd.py main set [--title ..] [--done-when ..] [--next-step ..] [--paused-for ..] [--set-by ..] [--note ..] --expected-version V --request-id R
    ocd.py render                   write the Markdown view again
    ocd.py import-md PATH           first migration from a hand-written <project>.md; rerunning it adds nothing

The store is $I_HAVE_OCD_HOME (default ~/.local/state/i-have-ocd)/<project>.db. The project is
--project, else $I_HAVE_OCD_PROJECT, else the repository around the working directory (all its
worktrees are one project), else the directory's name. --by (or $I_HAVE_OCD_BY) names who acts.

<project>.md beside the store is a generated view, written only after a change commits.
Sessions still on the old skill edit it by hand, so every command first reconciles a view that
changed since the helper wrote it: a line added under `## Parked` is parked, a removed line
closes its item with receipt `legacy-hand-removed`, and an edited main line becomes the main
line. A copy written back from an earlier read cannot close or overwrite what changed after the
store revision in its header; text the store declines is kept in a copy beside the view. The
output says so under `reconciled`, in the error JSON too; `count` prints it as one JSON line on
standard error.

Output is JSON. Exit 0 done; 1 store unavailable (missing, locked, damaged or not imported yet);
2 invalid request; 3 conflict (stale version, request id reused for another request, closed
item, lease held by someone else), with the current state.
"""
import argparse
import hashlib
import json
import os
import re
import shutil
import sqlite3
import subprocess
import sys
import uuid
from collections import Counter
from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from pathlib import Path

SCHEMA_VERSION = 1
BUSY_SECONDS = 10.0
PENDING = ("open", "taken")
STATUSES = ("open", "taken", "done", "dropped")
RECEIPT_KINDS = ("ticket", "pr", "scheduled", "resolved", "transferred", "recorded")
LEGACY_REMOVED = "legacy-hand-removed"
GENERATED = "<!-- GENERATED by i-have-ocd"
ITEM_ID = re.compile(r"(?:~~|\*\*|\[[ xX]\]\s*|[-*+]\s+)*P(\d+) ·")  # after strike-through, checkbox or bullet
REVISION = re.compile(r"store revision (\d+)\b")
RECENT_VIEWS = 32
MAIN_FIELDS = ("title", "done_when", "next_step", "paused_for", "set_by")
MAIN_LABELS = {"title": "title", "done_when": "done-when", "next_step": "next step", "paused_for": "paused-for",
               "set_by": "set"}
MAIN_KEYS = {"title": "title", "done when": "done_when", "next step": "next_step", "paused for": "paused_for",
             "set": "set_by", "set by": "set_by"}
MAIN_KEY = re.compile(r"([A-Za-z][A-Za-z _-]*?)\s*(\([^)]*\))?\s*:\s*(.*)", re.S)
SCHEMA = (
    """CREATE TABLE items (
        id INTEGER PRIMARY KEY AUTOINCREMENT, summary TEXT NOT NULL, source_refs TEXT NOT NULL,
        tracking_refs TEXT NOT NULL, needs_owner INTEGER NOT NULL, decision_ref TEXT,
        status TEXT NOT NULL CHECK (status IN ('open', 'taken', 'done', 'dropped')), version INTEGER NOT NULL,
        claim_holder TEXT, claim_token TEXT, claim_expires_at TEXT, receipt_kind TEXT, receipt_ref TEXT,
        created_at TEXT NOT NULL, created_by TEXT, updated_at TEXT NOT NULL, updated_by TEXT,
        closed_at TEXT, closed_by TEXT)""",
    """CREATE TABLE main_line (
        id INTEGER PRIMARY KEY CHECK (id = 1), title TEXT, done_when TEXT, next_step TEXT, paused_for TEXT,
        set_by TEXT, notes TEXT NOT NULL, version INTEGER NOT NULL, updated_at TEXT NOT NULL, updated_by TEXT)""",
    """CREATE TABLE events (
        seq INTEGER PRIMARY KEY AUTOINCREMENT, at TEXT NOT NULL, by TEXT, item_id INTEGER, action TEXT NOT NULL,
        version INTEGER, detail TEXT NOT NULL)""",
    """CREATE TABLE requests (
        request_id TEXT PRIMARY KEY, command TEXT NOT NULL, payload TEXT NOT NULL, result TEXT NOT NULL,
        at TEXT NOT NULL)""",
    "CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT)",
)


class Failure(Exception):
    code, kind = 1, "unavailable"

    def __init__(self, message, **state):
        super().__init__(message)
        self.state = state


class Unavailable(Failure):
    code, kind = 1, "unavailable"


class Invalid(Failure):
    code, kind = 2, "invalid"


class Conflict(Failure):
    code, kind = 3, "conflict"


def utcnow():
    return datetime.now(timezone.utc)


def iso(moment):
    return moment.strftime("%Y-%m-%dT%H:%M:%SZ")


def stamp():
    return utcnow().strftime("%Y%m%dT%H%M%SZ")


def digest(data):
    return None if data is None else hashlib.sha256(data).hexdigest()


def canonical(payload):
    return json.dumps(payload, sort_keys=True, ensure_ascii=False)


def flat(text):
    return " ".join(str(text).split())


def clean(values):
    return [v.strip() for v in values or [] if v and v.strip()]


def parse_ref(ref):
    match = re.fullmatch(r"[Pp]?(\d+)", str(ref).strip())
    if not match:
        raise Invalid(f"{ref!r} is not an item id; ids look like P12")
    return int(match.group(1))


def project_name(explicit):
    name = explicit or os.environ.get("I_HAVE_OCD_PROJECT") or repository_name() or Path.cwd().name
    if not name or name.startswith(".") or "/" in name or "\\" in name:
        raise Invalid(f"{name!r} cannot name a project store; pass --project")
    return name


def repository_name():
    """The repository around the working directory, named by its common git directory so every worktree agrees."""
    try:
        out = subprocess.run(["git", "rev-parse", "--git-common-dir"], capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.TimeoutExpired):
        return ""
    if out.returncode != 0 or not out.stdout.strip():
        return ""
    common = (Path.cwd() / out.stdout.strip()).resolve()
    return common.parent.name if common.name == ".git" else common.name.removesuffix(".git")


def sections(text):
    """`## ` heading (lower case) -> the lines under it."""
    found, current = {}, None
    for line in text.splitlines():
        if line.startswith("## "):
            current = line[3:].strip().lower()
            found.setdefault(current, [])
        elif current is not None:
            found[current].append(line)
    return found


def blocks(lines):
    """Each `- ` bullet with the indented lines that continue it; stray text is a block of its own."""
    found, bullet = [], False
    for line in lines or []:
        if not line.strip():
            continue
        if line.startswith("- "):
            found.append(line[2:].strip())
            bullet = True
        elif bullet and line[:1].isspace():
            found[-1] += "\n" + line.strip()
        else:
            found.append(line.strip())
            bullet = False
    return found


def generated(path):
    with open(path, "rb") as handle:
        return handle.read(len(GENERATED)) == GENERATED.encode()


def section_text(lines):
    return "\n".join(line.rstrip() for line in lines or []).strip()


def parse_main(lines):
    """Main-line fields from `- key: value` bullets; every other line is kept as a note, verbatim."""
    main, notes = dict.fromkeys(MAIN_FIELDS, ""), []
    for block in blocks(lines):
        match = MAIN_KEY.fullmatch(block)
        field = MAIN_KEYS.get(" ".join(re.split(r"[-_ ]+", match.group(1).lower())).strip()) if match else None
        if field and not main[field]:
            main[field] = f"{match.group(2)} {match.group(3)}".strip() if match.group(2) else match.group(3).strip()
        else:
            notes.append(block)
    return {**main, "notes": notes}


def item_text(item):
    """The item's one line in the view, led by its id."""
    parts = [f"{item['ref']} · {flat(item['summary'])}"]
    if item["source_refs"]:
        parts.append("sources: " + "; ".join(flat(s) for s in item["source_refs"]))
    if item["tracking_refs"]:
        parts.append("tracking: " + "; ".join(flat(t) for t in item["tracking_refs"]))
    if item["needs_owner"]:
        parts.append("owner decides")
    if item["decision_ref"]:
        parts.append("ruled: " + flat(item["decision_ref"]))
    if item["claim"]:
        parts.append(f"taken by {item['claim']['holder']} until {item['claim']['expires_at']}")
    return " · ".join(parts)


def ignored_why(item):
    return "listed twice" if item["status"] in PENDING else f"{item['status']}; a closed item is never reopened"


def main_lines(main):
    if not main:
        return []
    lines = [f"- {MAIN_LABELS[f]}: {flat(main[f])}" for f in MAIN_FIELDS if main[f]]
    return lines + ["- " + note.replace("\n", "\n  ") for note in main["notes"]]


class Store:
    def __init__(self, project, by):
        self.project, self.by = project, by
        home = Path(os.environ.get("I_HAVE_OCD_HOME") or "~/.local/state/i-have-ocd").expanduser().resolve()
        self.path, self.view = home / f"{project}.db", home / f"{project}.md"
        self.db, self.rendered, self.aside, self.reconciled = None, None, None, {}

    # -- connection and transactions

    def open(self, create=False, guard_view=True):
        if not self.path.exists():
            if not create:
                raise Unavailable(f"no store at {self.path}; park, main set or import-md creates it")
            if guard_view and self.view.exists() and not generated(self.view):
                raise Unavailable(f"{self.view} was written by hand and has not been imported; "
                                  f"run `ocd.py import-md {self.view}` first")
            self.create()
        self.db = sqlite3.connect(self.path.as_uri() + "?mode=rw", uri=True, timeout=BUSY_SECONDS,
                                  isolation_level=None)
        self.db.row_factory = sqlite3.Row
        self.db.execute(f"PRAGMA busy_timeout = {int(BUSY_SECONDS * 1000)}")
        schema = self.db.execute("PRAGMA user_version").fetchone()[0]
        if schema != SCHEMA_VERSION:
            raise Unavailable(f"{self.path} is not an i-have-ocd store of schema {SCHEMA_VERSION} (found {schema})")
        return self

    def create(self):
        """Build the store aside, already in WAL mode, and link it into place: sessions that start at the same
        moment never race to switch the journal mode or write the schema, and the first link wins."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        fresh = self.path.with_name(f"{self.path.name}.{os.getpid()}.new")
        fresh.unlink(missing_ok=True)  # left by a process that died here with the same pid
        db = sqlite3.connect(fresh)
        try:
            db.execute("PRAGMA journal_mode = WAL")
            for statement in SCHEMA:
                db.execute(statement)
            db.execute(f"PRAGMA user_version = {SCHEMA_VERSION}")
            db.commit()
        finally:
            db.close()
        try:
            os.link(fresh, self.path)
        except FileExistsError:
            pass
        finally:
            fresh.unlink()

    def close(self):
        if self.db is not None:
            self.db.close()

    @contextmanager
    def transaction(self):
        """BEGIN IMMEDIATE: one writer at a time. The view it renders reaches the file only after COMMIT, so a
        command that dies before COMMIT leaves the file as it was, never showing a change that did not happen."""
        self.db.execute("BEGIN IMMEDIATE")
        self.rendered = None
        try:
            yield
            self.db.execute("COMMIT")
        except BaseException:
            if self.db.in_transaction:
                self.db.execute("ROLLBACK")
            self.rendered = None
            raise
        if self.rendered is not None:
            data, self.rendered = self.rendered, None
            self.publish(data)

    def publish(self, data):
        """Write a committed render, unless a later command rendered since (its own write follows)."""
        try:
            self.db.execute("BEGIN IMMEDIATE")
            try:
                if self.meta("view_hash") == digest(data):
                    self.write_file(data)
            finally:
                self.db.execute("COMMIT")
        except (OSError, sqlite3.Error) as error:
            raise Unavailable(f"the change is committed, but {self.view} was not written ({error}); the next "
                              "command writes it", committed=True)

    def mutate(self, command, request_id, payload, apply, create=False):
        """One change: take in a hand-edited view, replay a known request id or apply, record it, render."""
        if not request_id or not request_id.strip():
            raise Invalid("every change needs --request-id")
        self.open(create)
        self.sync()
        with self.transaction():
            result = self.replay(command, request_id, payload)
            if result is None:
                result = apply()
                self.remember(request_id, command, payload, result)
            self.settle()
        return result

    def replay(self, command, request_id, payload):
        row = self.db.execute("SELECT command, payload, result FROM requests WHERE request_id = ?",
                              (request_id,)).fetchone()
        if row is None:
            return None
        if row["command"] == command and row["payload"] == canonical(payload):
            return {**json.loads(row["result"]), "replayed": True}
        item = self.item(payload["item"]) if payload.get("item") else None
        original = {k: v for k, v in json.loads(row["result"]).items() if k != "token"}  # only its own take shows it
        raise Conflict(f"request id {request_id} was already used for a different {row['command']} request",
                       original=original, current=self.public(item) if item else None)

    def remember(self, request_id, command, payload, result):
        self.db.execute("INSERT INTO requests VALUES (?, ?, ?, ?, ?)", (
            request_id, command, canonical(payload), json.dumps(result, ensure_ascii=False), iso(utcnow())))

    # -- rows

    def meta(self, key):
        row = self.db.execute("SELECT value FROM meta WHERE key = ?", (key,)).fetchone()
        return row["value"] if row else None

    def set_meta(self, **values):
        for key, value in values.items():
            self.db.execute("INSERT OR REPLACE INTO meta VALUES (?, ?)", (key, value))

    def revision(self):
        return self.db.execute("SELECT COALESCE(MAX(seq), 0) FROM events").fetchone()[0]

    def event(self, item_id, action, version, detail):
        self.db.execute("INSERT INTO events (at, by, item_id, action, version, detail) VALUES (?, ?, ?, ?, ?, ?)",
                        (iso(utcnow()), self.by, item_id, action, version, json.dumps(detail, ensure_ascii=False)))

    def last_event(self, item_id, first=False):
        """The seq of an item's last (or first, its creation) history event; item None is the main line."""
        return self.db.execute(f"SELECT {'MIN' if first else 'MAX'}(seq) FROM events WHERE item_id IS ?",
                               (item_id,)).fetchone()[0] or 0

    def item(self, item_id):
        row = self.db.execute("SELECT * FROM items WHERE id = ?", (item_id,)).fetchone()
        return self.row_item(row) if row else None

    def row_item(self, row):
        item = {"id": row["id"], "ref": f"P{row['id']}", **dict(row)}
        item.update(source_refs=json.loads(row["source_refs"]), tracking_refs=json.loads(row["tracking_refs"]),
                    needs_owner=bool(row["needs_owner"]))
        item["claim"] = {"holder": row["claim_holder"], "expires_at": row["claim_expires_at"],
                         "expired": row["claim_expires_at"] <= iso(utcnow())} if row["status"] == "taken" else None
        item["receipt"] = {"kind": row["receipt_kind"], "ref": row["receipt_ref"]} if row["receipt_kind"] else None
        return item

    def items(self, statuses=STATUSES):
        rows = self.db.execute(f"SELECT * FROM items WHERE status IN ({', '.join('?' * len(statuses))}) ORDER BY id",
                               statuses).fetchall()
        return [self.row_item(row) for row in rows]

    def items_with_summary(self, summary):
        return [self.row_item(row) for row in self.db.execute("SELECT * FROM items WHERE summary = ? ORDER BY id",
                                                              (summary,))]

    @staticmethod
    def public(item):
        """An item as commands print it: claim and receipt as objects, and no lease token, which only `take` hands out."""
        return {k: v for k, v in item.items() if not k.startswith(("claim_", "receipt_"))}

    def insert(self, summary, sources, tracking, needs_owner, action):
        now = iso(utcnow())
        cursor = self.db.execute(
            "INSERT INTO items (summary, source_refs, tracking_refs, needs_owner, status, version, created_at, "
            "created_by, updated_at, updated_by) VALUES (?, ?, ?, ?, 'open', 1, ?, ?, ?, ?)",
            (summary, json.dumps(sources, ensure_ascii=False), json.dumps(tracking, ensure_ascii=False),
             int(needs_owner), now, self.by, now, self.by))
        self.event(cursor.lastrowid, action, 1, {"summary": summary, "source_refs": sources,
                                                 "tracking_refs": tracking, "needs_owner": needs_owner})
        return self.item(cursor.lastrowid)

    def change(self, item, changes, action, detail=None):
        """Write the changes with the next version and a history event, in the caller's transaction."""
        version = item["version"] + 1
        row = {k: json.dumps(v, ensure_ascii=False) if isinstance(v, list) else v for k, v in changes.items()}
        row.update(version=version, updated_at=iso(utcnow()), updated_by=self.by)
        self.db.execute(f"UPDATE items SET {', '.join(f'{k} = ?' for k in row)} WHERE id = ?",
                        (*row.values(), item["id"]))
        self.event(item["id"], action, version, changes if detail is None else detail)
        return self.item(item["id"])

    def close_item(self, item, status, kind, ref, action, **extra):
        return self.change(item, {"status": status, "receipt_kind": kind, "receipt_ref": ref,
                                  "closed_at": iso(utcnow()), "closed_by": self.by, **extra},
                           action, {"status": status, "receipt": {"kind": kind, "ref": ref}, **extra})

    def pending(self, ref, expected_version, token=None, check_claim=True):
        """The item a change names, refused when it is closed, when the caller read an older version, or when
        another session holds it: a lease that is still running, or a token that is not the caller's."""
        item = self.item(ref)
        if item is None:
            raise Invalid(f"no item P{ref}")
        if item["status"] not in PENDING:
            raise Conflict(f"{item['ref']} is {item['status']}; a closed item is never reopened: park a new item "
                           f"that cites {item['ref']}", current=self.public(item))
        if item["version"] != expected_version:
            raise Conflict(f"{item['ref']} is at version {item['version']}, not {expected_version}: read it again "
                           "and decide again", current=self.public(item))
        if check_claim:
            if token and (token != item["claim_token"] or item["claim_holder"] != self.by):
                raise Conflict(f"stale holder: {item['ref']} is not held by {self.by or 'you'} with that token",
                               current=self.public(item))
            if not token and item["claim"] and not item["claim"]["expired"]:
                raise Conflict(f"{item['ref']} is held by {item['claim']['holder']} until "
                               f"{item['claim']['expires_at']}; pass its --token or wait for the lease to expire",
                               current=self.public(item))
        return item

    def main(self):
        row = self.db.execute("SELECT * FROM main_line WHERE id = 1").fetchone()
        if row is None:
            return None
        main = {k: row[k] for k in (*MAIN_FIELDS, "version", "updated_at", "updated_by")}
        return {**main, "notes": json.loads(row["notes"])}

    def write_main(self, fields, action):
        current = self.main()
        base = current or {**dict.fromkeys(MAIN_FIELDS, ""), "notes": [], "version": 0}
        new = {**{k: base[k] for k in (*MAIN_FIELDS, "notes")}, **fields}
        version = base["version"] + 1
        self.db.execute("INSERT OR REPLACE INTO main_line VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?)", (
            *(new[f] for f in MAIN_FIELDS), json.dumps(new["notes"], ensure_ascii=False), version,
            iso(utcnow()), self.by))
        self.event(None, action, version, fields)
        return self.main()

    # -- the Markdown view

    def write_file(self, data):
        tmp = self.view.with_name(f"{self.view.name}.{os.getpid()}.tmp")
        tmp.write_bytes(data)
        os.replace(tmp, self.view)

    def render(self):
        """Render <project>.md from the store (the main line, then the pending items by id) and record it as the
        view; the file is written once the transaction commits."""
        main, pending = self.main(), self.items(PENDING)
        lines, view_items = main_lines(main), {str(item["id"]): item_text(item) for item in pending}
        text = "\n".join([
            f"{GENERATED} from {self.path.name} by scripts/ocd.py, store revision {self.revision()}. Read-only: park "
            "and close items with the helper; a hand edit here is taken into the store by its next command. -->",
            f"# {self.project}: main line and parked items (this machine only)", "", "## Main line", *lines, "",
            "## Parked", *("- " + line for line in view_items.values())]) + "\n"
        data = text.encode("utf-8")
        recent = [digest(data)] + json.loads(self.meta("recent_views") or "[]")
        self.set_meta(view_hash=digest(data), view_items=json.dumps(view_items, ensure_ascii=False),
                      view_main=section_text(lines), recent_views=json.dumps(recent[:RECENT_VIEWS]))
        self.rendered = data

    def sync(self):
        """Take in a view edited by hand and write it again; nothing to do while it is what the helper wrote."""
        if digest(self.view.read_bytes() if self.view.exists() else None) == self.meta("view_hash"):
            return
        with self.transaction():
            if self.reconcile():
                self.render()

    def settle(self):
        """Inside a change: take in edits made to the view meanwhile, then render it."""
        for _ in range(3):
            if not self.reconcile():
                break
        self.render()

    def note(self, kind, value):
        if kind in ("parked", "edited", "closed", "ignored", "stale", "set_aside"):
            self.reconciled.setdefault(kind, []).append(value)
        else:
            self.reconciled[kind] = value

    def copy_aside(self, source, kind):
        """Copy a file beside the view under a name no other copy has; returns its path."""
        backup = self.view.with_name(f"{self.view.name}.{kind}-{stamp()}")
        while backup.exists():
            backup = backup.with_name(backup.name + "+")
        shutil.copyfile(source, backup)
        return str(backup)

    def set_aside(self, kind="stale"):
        """Keep the edited view in a copy before the store declines part of it, once per reconcile."""
        if self.aside is None:
            self.aside = self.copy_aside(self.view, kind)
            self.note("set_aside", self.aside)
        return self.aside

    def reconcile(self):
        """Take a hand edit of the view into the store. False while the view is what the helper last wrote.

        A file that is an earlier render nobody edited (a write overtaken by a later command, or lost when a
        command died after COMMIT) is only written again. Otherwise the file may be a whole copy written back
        from an earlier read, so its header's store revision N says what that copy could show; a header above
        the store's revision is a render that never committed and is only set aside. A line under `## Parked`
        stands for the item its P<n> names (after any ~~, [x] or bullet markup), else for an item whose summary
        it repeats word for word (a line written before the import); any other line is parked as new.

        - A changed line is an edit only if its item has not changed since N, else it is `stale`.
        - An item whose line is gone closes as `legacy-hand-removed` only if it has not changed since N and
          no live lease holds it; one that changed since N is `stale`, and one created after N was never in
          the copy.
        - A line naming a closed item, or repeating an item listed above, is ignored when it is that item's
          line; with other text it is parked as a new item citing the old id, unless the item closed after N,
          when it is `stale`.
        - A changed main-line section becomes the main line only if the main line has not changed since N,
          else `main_conflict`.
        - A copy without a readable revision (`no_revision`) closes nothing and changes no main line.

        Text the store declines (stale lines, a main-line conflict, sections it does not read) stays in a copy
        set aside beside the view, and the report names it.
        """
        data = self.view.read_bytes() if self.view.exists() else None
        recorded = self.meta("view_hash")
        if digest(data) == recorded:
            return False
        if data is None:
            return True
        if digest(data) in json.loads(self.meta("recent_views") or "[]"):
            self.set_meta(view_hash=digest(data))
            return True
        text = data.decode("utf-8", errors="replace")
        if recorded is None and not text.startswith(GENERATED):
            raise Unavailable(f"{self.view} was written by hand and has not been imported; "
                              f"run `ocd.py import-md {self.view}` first")
        self.aside = None
        parts = sections(text)
        header = REVISION.search(text.split("\n", 1)[0]) if text.startswith(GENERATED) else None
        shown_at = int(header.group(1)) if header else None  # the store revision this copy was rendered at
        if "parked" not in parts:
            self.note("unreadable", self.set_aside("unreadable"))
            self.set_meta(view_hash=digest(data))
            return True
        if shown_at is not None and shown_at > self.revision():
            self.note("uncommitted_view", self.set_aside("uncommitted"))
            self.set_meta(view_hash=digest(data))
            return True
        if shown_at is None:
            self.note("no_revision", self.set_aside())
        others = [name for name, lines in parts.items() if name not in ("main line", "parked") and section_text(lines)]
        if others:
            self.note("other_sections", others)
            self.set_aside()
        rendered = json.loads(self.meta("view_items") or "{}")
        seen, view_items = set(), {}
        for block in blocks(parts["parked"]):
            item = self.take_in(block, rendered, seen, shown_at)
            if item is not None:
                seen.add(item["id"])
                view_items[str(item["id"])] = block
        for key in rendered:
            item = self.item(int(key)) if int(key) not in seen else None
            if not item or item["status"] not in PENDING or shown_at is None:
                continue
            held = item["claim"] and not item["claim"]["expired"]
            if self.last_event(item["id"]) <= shown_at and not held:
                self.close_item(item, "done", LEGACY_REMOVED, self.view.name, "reconcile-close")
                self.note("closed", item["ref"])
            elif self.last_event(item["id"], first=True) <= shown_at:
                self.note("stale", item["ref"])
                self.set_aside()
        main_section = section_text(parts.get("main line"))
        if "main line" in parts and main_section != self.meta("view_main") and shown_at is not None:
            fields, current = parse_main(parts["main line"]), self.main()
            changed = current is None or any(current[k] != v for k, v in fields.items())
            if changed and self.last_event(None) > shown_at:
                self.note("main_conflict", self.set_aside())
            elif changed:
                self.write_main(fields, "reconcile-main")
                self.note("main", True)
        self.set_meta(view_hash=digest(data), view_items=json.dumps(view_items, ensure_ascii=False),
                      view_main=main_section)
        return True

    def take_in(self, block, rendered, seen, shown_at):
        """Apply one `## Parked` line of an edited view; returns the item it stands for, or None if it is ignored."""
        found = ITEM_ID.match(block)
        named = self.item(int(found.group(1))) if found else None
        if named and named["status"] in PENDING and named["id"] not in seen:
            line = rendered.get(str(named["id"]))
            if line is None or block == line:
                return named
            if shown_at is None or self.last_event(named["id"]) > shown_at:
                self.note("stale", named["ref"])
                self.set_aside()
                return named
            added = block[len(line):].strip(" ;·,") if block.startswith(line) else block
            source = f"hand-edited {self.view.name}: {added}"
            self.note("edited", named["ref"])
            return self.change(named, {"source_refs": named["source_refs"] + [source]}, "reconcile-edit",
                               {"source": source})
        if named:
            if block in (rendered.get(str(named["id"])), item_text(named)):
                self.note("ignored", f"{named['ref']}: {ignored_why(named)}")
                return None
            if named["status"] not in PENDING and (shown_at is None or self.last_event(named["id"]) > shown_at):
                self.note("stale", named["ref"])
                self.set_aside()
                return None
            item = self.insert(block, [f"hand-edited {self.view.name}; cites {named['ref']}"], [], False,
                               "reconcile-park")
            self.note("parked", item["ref"])
            return item
        same = self.items_with_summary(block)
        for item in same:
            if item["status"] in PENDING and item["id"] not in seen:
                return item
        if same:
            self.note("ignored", f"{same[0]['ref']}: {ignored_why(same[0])}")
            return None
        item = self.insert(block, [f"hand-edited {self.view.name}"], [], False, "reconcile-park")
        self.note("parked", item["ref"])
        return item


# -- commands


def cmd_park(store, args):
    summary = (args.summary or "").strip()
    if not summary:
        raise Invalid("park needs the item's line")
    payload = {"summary": summary, "source_refs": clean(args.source), "tracking_refs": clean(args.tracking),
               "needs_owner": args.needs_owner}
    return store.mutate("park", args.request_id, payload, lambda: {"item": store.public(store.insert(
        summary, payload["source_refs"], payload["tracking_refs"], args.needs_owner, "park"))}, create=True)


def cmd_add_source(store, args):
    payload = {"item": parse_ref(args.item), "source_refs": clean(args.source), "tracking_refs": clean(args.tracking),
               "expected_version": args.expected_version}
    if not payload["source_refs"] and not payload["tracking_refs"]:
        raise Invalid("add-source needs --source or --tracking")

    def apply():
        item = store.pending(payload["item"], args.expected_version, check_claim=False)
        sources = [s for s in payload["source_refs"] if s not in item["source_refs"]]
        tracking = [t for t in payload["tracking_refs"] if t not in item["tracking_refs"]]
        if not sources and not tracking:
            return {"item": store.public(item), "unchanged": True}
        item = store.change(item, {"source_refs": item["source_refs"] + sources,
                                   "tracking_refs": item["tracking_refs"] + tracking}, "add-source",
                            {"source_refs": sources, "tracking_refs": tracking})
        return {"item": store.public(item)}
    return store.mutate("add-source", args.request_id, payload, apply)


def cmd_take(store, args):
    if not store.by:
        raise Invalid("take needs --by or I_HAVE_OCD_BY to name the holder")
    if args.ttl_minutes <= 0:
        raise Invalid("--ttl-minutes must be positive")
    payload = {"item": parse_ref(args.item), "expected_version": args.expected_version, "holder": store.by,
               "ttl_minutes": args.ttl_minutes}

    def apply():
        item = store.pending(payload["item"], args.expected_version, check_claim=False)
        if item["claim"] and not item["claim"]["expired"]:
            raise Conflict(f"{item['ref']} is held by {item['claim']['holder']} until {item['claim']['expires_at']}",
                           current=store.public(item))
        token, expires = uuid.uuid4().hex, iso(utcnow() + timedelta(minutes=args.ttl_minutes))
        item = store.change(item, {"status": "taken", "claim_holder": store.by, "claim_token": token,
                                   "claim_expires_at": expires}, "take", {"holder": store.by, "expires_at": expires})
        return {"item": store.public(item), "token": token}
    return store.mutate("take", args.request_id, payload, apply)


def cmd_decide(store, args):
    ref = (args.ref or "").strip()
    if not ref:
        raise Invalid("decide needs --ref: where the owner's ruling is recorded")
    payload = {"item": parse_ref(args.item), "decision_ref": ref, "expected_version": args.expected_version}

    def apply():  # a ruling neither handles nor closes the item, so a lease does not stop it; the version does
        item = store.pending(payload["item"], args.expected_version, check_claim=False)
        return {"item": store.public(store.change(item, {"decision_ref": ref, "needs_owner": False}, "decide"))}
    return store.mutate("decide", args.request_id, payload, apply)


def cmd_done(store, args):
    kind, ref = (args.kind or "").strip(), (args.ref or "").strip()
    if kind not in RECEIPT_KINDS or not ref:
        raise Invalid(f"done needs a receipt: --kind one of {', '.join(RECEIPT_KINDS)} and a non-empty --ref "
                      "(the ticket, PR, schedule id or record that now carries the item)")
    payload = {"item": parse_ref(args.item), "kind": kind, "ref": ref, "expected_version": args.expected_version,
               "token": args.token}

    def apply():
        item = store.pending(payload["item"], args.expected_version, args.token)
        return {"item": store.public(store.close_item(item, "done", kind, ref, "done"))}
    return store.mutate("done", args.request_id, payload, apply)


def cmd_drop(store, args):
    decision = (args.decision or "").strip()
    if not decision:
        raise Invalid("drop needs --decision: where the owner's ruling to drop it is recorded")
    payload = {"item": parse_ref(args.item), "decision_ref": decision, "expected_version": args.expected_version,
               "token": args.token}

    def apply():
        item = store.pending(payload["item"], args.expected_version, args.token)
        return {"item": store.public(store.close_item(item, "dropped", "dropped", decision, "drop",
                                                      decision_ref=decision))}
    return store.mutate("drop", args.request_id, payload, apply)


def cmd_list(store, args):
    store.open()
    store.sync()
    everything = store.items()
    counts = Counter(item["status"] for item in everything)
    pending = [item for item in everything if item["status"] in PENDING]
    return {"project": store.project, "store": str(store.path), "revision": store.revision(),
            "counts": {**{s: counts[s] for s in STATUSES}, "pending": len(pending),
                       "needs_owner": sum(1 for item in pending if item["needs_owner"])},
            "items": [store.public(item) for item in (everything if args.all else pending)]}


def cmd_show(store, args):
    store.open()
    store.sync()
    item = store.item(parse_ref(args.item))
    if item is None:
        raise Invalid(f"no item {args.item}")
    history = [{**dict(row), "detail": json.loads(row["detail"])} for row in store.db.execute(
        "SELECT seq, at, by, action, version, detail FROM events WHERE item_id = ? ORDER BY seq", (item["id"],))]
    return {"item": store.public(item), "history": history, "revision": store.revision()}


def cmd_count(store, args):
    store.open()
    store.sync()
    return store.db.execute("SELECT count(*) FROM items WHERE status IN ('open', 'taken')").fetchone()[0]


def cmd_main_get(store, args):
    store.open()
    store.sync()
    main = store.main()
    return {"main": main, "version": main["version"] if main else 0, "revision": store.revision()}


def cmd_main_set(store, args):
    fields = {f: getattr(args, f).strip() for f in MAIN_FIELDS if getattr(args, f) is not None}
    if args.note is not None or args.clear_notes:
        fields["notes"] = clean(args.note)
    if not fields:
        raise Invalid("main set needs at least one field")
    payload = {**fields, "expected_version": args.expected_version}

    def apply():
        current = store.main()
        version = current["version"] if current else 0
        if version != args.expected_version:
            raise Conflict(f"the main line is at version {version}, not {args.expected_version}: read it again",
                           current=current)
        return {"main": store.write_main(fields, "main-set")}
    return store.mutate("main-set", args.request_id, payload, apply, create=True)


def cmd_render(store, args):
    store.open()
    store.sync()
    with store.transaction():
        store.settle()
    return {"view": str(store.view), "hash": store.meta("view_hash"), "revision": store.revision()}


def cmd_import_md(store, args):
    """First migration: every line under `## Parked` becomes one item, verbatim; the main-line section becomes the
    main line. Request ids come from the text and a line whose summary a pending item already has is that item,
    so a rerun, or a later copy of the same file, adds only new lines; a line of a closed item is not reopened.
    The main line comes from the file only while no command but import-md has written one."""
    source = Path(args.path).expanduser()
    try:
        text = source.read_text(encoding="utf-8")
    except OSError as error:
        raise Invalid(f"cannot read {source}: {error}")
    if text.startswith(GENERATED):
        raise Invalid(f"{source} is a view this helper generated; import the hand-written file")
    parts = sections(text)
    if "parked" not in parts and any(name.startswith("parked") for name in parts):
        raise Invalid(f"{source} has no `## Parked` heading but has "
                      f"{', '.join('`## ' + n + '`' for n in parts if n.startswith('parked'))}; rename it to "
                      "`## Parked` so its items are imported")
    if "parked" not in parts and "main line" not in parts:
        raise Invalid(f"{source} has no `## Main line` or `## Parked` section")
    view_is_source = store.view.exists() and os.path.samefile(store.view, source)
    store.open(create=True, guard_view=False)
    result = {"imported": [], "already": [], "ignored": [], "main": "absent",
              "ignored_sections": [name for name in parts if name not in ("main line", "parked")]}
    with store.transaction():
        # checked under the write lock: another import-md may have replaced the view since this one read it
        recorded = store.meta("view_hash")
        hand_written_view = store.view.exists() and not generated(store.view)
        if view_is_source and hand_written_view and recorded is not None:
            raise Invalid(f"{source} is this store's view; a hand edit to it is taken in by any command, such as "
                          "render")
        if hand_written_view and not view_is_source and recorded is None:
            raise Unavailable(f"{store.view} is hand-written too; import it as well (`ocd.py import-md {store.view}`)")
        replacing = hand_written_view and recorded is None
        if not replacing:
            for _ in range(3):
                if not store.reconcile():
                    break
        occurrences, seen = Counter(), set()
        for block in blocks(parts.get("parked")):
            occurrences[block] += 1
            request_id = "import-md:" + hashlib.sha256(f"{occurrences[block]}\n{block}".encode()).hexdigest()[:32]
            payload = {"summary": block, "source_refs": [f"legacy {store.project}.md"]}
            known = store.replay("import-md", request_id, payload)
            same = [] if known else store.items_with_summary(block)
            match = next((i for i in same if i["status"] in PENDING and i["id"] not in seen), None)
            if known or match:
                if match:
                    store.remember(request_id, "import-md", payload, {"item": store.public(match)})
                ref = known["item"]["ref"] if known else match["ref"]
                result["already"].append(ref)
                seen.add(int(ref[1:]))
            elif any(i["status"] not in PENDING for i in same):
                closed = next(i for i in same if i["status"] not in PENDING)
                result["ignored"].append(f"{closed['ref']}: {ignored_why(closed)}")
            else:
                item = store.insert(block, payload["source_refs"], [], False, "import-md")
                store.remember(request_id, "import-md", payload, {"item": store.public(item)})
                result["imported"].append(item["ref"])
                seen.add(item["id"])
        if replacing:
            result["backup"] = store.copy_aside(store.view, "pre-import")
        if "main line" in parts:
            fields = parse_main(parts["main line"])
            request_id = "import-md:main:" + hashlib.sha256(section_text(parts["main line"]).encode()).hexdigest()[:32]
            last = store.db.execute("SELECT action FROM events WHERE item_id IS NULL ORDER BY seq DESC LIMIT 1").fetchone()
            if store.replay("import-md-main", request_id, fields):
                result["main"] = "unchanged"
            elif last is None or last["action"] == "import-md":
                store.remember(request_id, "import-md-main", fields, {"main": store.write_main(fields, "import-md")})
                result["main"] = "set"
            else:
                result["main"] = "conflict"
                result["main_conflict"] = result.get("backup") or store.copy_aside(source, "import-main")
        store.render()
    return {**result, "view": str(store.view), "revision": store.revision()}


# -- output


def list_text(result):
    counts = result["counts"]
    head = (f"{result['project']}: {counts['pending']} pending ({counts['open']} open, {counts['taken']} taken; "
            f"{counts['needs_owner']} for the owner to decide) · revision {result['revision']}")
    return "\n".join([head] + [f"- [{i['status']} v{i['version']}] {item_text(i)}" for i in result["items"]])


def show_text(result):
    item = result["item"]
    lines = [f"{item_text(item)}", f"status {item['status']}, version {item['version']}"]
    if item["receipt"]:
        lines.append(f"receipt: {item['receipt']['kind']} {item['receipt']['ref']}")
    lines += [f"  {e['at']} {e['by'] or '-'}: {e['action']} v{e['version']} {json.dumps(e['detail'], ensure_ascii=False)}"
              for e in result["history"]]
    return "\n".join(lines)


def main_text(result):
    if not result["main"]:
        return "no main line set"
    return "\n".join([f"main line v{result['version']}", *main_lines(result["main"])])


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--project", default="", help="store name; default: $I_HAVE_OCD_PROJECT, else the repository")
    common.add_argument("--by", default="", help="who acts, kept in the history; default: $I_HAVE_OCD_BY")
    change = argparse.ArgumentParser(add_help=False)
    change.add_argument("--request-id", required=True, help="your id for this change; a retry reuses it")
    versioned = argparse.ArgumentParser(add_help=False, parents=[change])
    versioned.add_argument("--expected-version", type=int, required=True, help="the version you read")
    held = argparse.ArgumentParser(add_help=False)
    held.add_argument("--token", default="", help="the lease token `take` printed, when you hold the item")
    sub = parser.add_subparsers(dest="command", required=True)

    def command(name, func, *parents, **kwargs):
        p = sub.add_parser(name, parents=[common, *parents], **kwargs)
        p.set_defaults(func=func)
        return p

    p = command("park", cmd_park, change, help="park a new item")
    p.add_argument("summary", help="one line: what it is, why it matters, where it was seen")
    p.add_argument("--source", action="append", help="where it was seen (file:line, run, issue, message); repeatable")
    p.add_argument("--tracking", action="append", help="a ticket or PR that carries related work; repeatable")
    p.add_argument("--needs-owner", action="store_true", help="the owner must decide something")
    p = command("add-source", cmd_add_source, versioned, help="add a source to the same concern")
    p.add_argument("item")
    p.add_argument("--source", action="append")
    p.add_argument("--tracking", action="append")
    p = command("list", cmd_list, help="pending items, counts and the store revision")
    p.add_argument("--all", action="store_true", help="closed items too")
    p.add_argument("--text", action="store_true")
    p = command("show", cmd_show, help="one item and its history")
    p.add_argument("item")
    p.add_argument("--text", action="store_true")
    command("count", cmd_count, help="the pending number; ? when the store cannot be read")
    p = command("take", cmd_take, versioned, help="hold an item under a lease while you handle it")
    p.add_argument("item")
    p.add_argument("--ttl-minutes", type=int, default=60)
    p = command("decide", cmd_decide, versioned, help="record the owner's ruling; the item stays pending")
    p.add_argument("item")
    p.add_argument("--ref", default="", help="where the ruling is recorded")
    p = command("done", cmd_done, versioned, held, help="close a handled item with its receipt")
    p.add_argument("item")
    p.add_argument("--kind", default="", help=" | ".join(RECEIPT_KINDS))
    p.add_argument("--ref", default="", help="the ticket, PR, schedule id or record")
    p = command("drop", cmd_drop, versioned, held, help="close an item the owner dropped")
    p.add_argument("item")
    p.add_argument("--decision", default="", help="where the owner's ruling is recorded")
    main_parser = sub.add_parser("main", help="the main line")
    main_sub = main_parser.add_subparsers(dest="main_command", required=True)
    p = main_sub.add_parser("get", parents=[common])
    p.add_argument("--text", action="store_true")
    p.set_defaults(func=cmd_main_get)
    p = main_sub.add_parser("set", parents=[common, versioned], help="change the given fields")
    for field in MAIN_FIELDS:
        p.add_argument("--" + field.replace("_", "-"), dest=field, default=None)
    p.add_argument("--note", action="append", help="replaces the notes; repeatable")
    p.add_argument("--clear-notes", action="store_true")
    p.set_defaults(func=cmd_main_set)
    command("render", cmd_render, help="write the Markdown view again")
    p = command("import-md", cmd_import_md, help="first migration from a hand-written <project>.md")
    p.add_argument("path")
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    store = None
    try:
        store = Store(project_name(args.project), args.by or os.environ.get("I_HAVE_OCD_BY", ""))
        try:
            result = args.func(store, args)
        except (sqlite3.Error, OSError) as error:
            locked = "locked" in str(error) or "busy" in str(error)
            raise Unavailable(f"store {'is locked by another writer' if locked else 'cannot be used'}: {error}")
    except Exception as error:
        failure = error if isinstance(error, Failure) else Unavailable(f"{type(error).__name__}: {error}")
        reconciled = store.reconciled if store is not None else {}  # a sync may have committed before the failure
        if args.command == "count":
            print("?")
        elif isinstance(error, Failure):
            print(json.dumps({"ok": False, "error": failure.kind, "message": str(failure), **failure.state,
                              **({"reconciled": reconciled} if reconciled else {})}, ensure_ascii=False, indent=2))
        else:
            raise
        print(f"ocd.py: {failure}", file=sys.stderr)
        if args.command == "count" and reconciled:
            print(json.dumps({"reconciled": reconciled}, ensure_ascii=False), file=sys.stderr)
        return failure.code
    finally:
        if store is not None:
            store.close()
    if args.command == "count":
        print(result)
        if store.reconciled:
            print(json.dumps({"reconciled": store.reconciled}, ensure_ascii=False), file=sys.stderr)
        return 0
    if store.reconciled:
        result["reconciled"] = store.reconciled
    if getattr(args, "text", False):
        print({"list": list_text, "show": show_text, "main": main_text}[args.command](result))
        if store.reconciled:
            print("hand edits of the view taken in: " + json.dumps(store.reconciled, ensure_ascii=False))
    else:
        print(json.dumps({"ok": True, **result}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
